spring.application.name=proyectoOvi
# Connexió a db-aules
spring.datasource.type=org.springframework.jdbc.datasource.DriverManagerDataSource
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.jdbcUrl=jdbc:postgresql://db-aules.uji.es:5432/ei102725jhd
spring.datasource.username=ei102725jhd
spring.datasource.password=ei102725jhd