spring.application.name=proyectoOvi

# URL para Spring gen�rico
spring.datasource.url=jdbc:postgresql://db-aules.uji.es:5432/ei102725jhd
# URL expl�cita para que Hikari no se queje
spring.datasource.hikari.jdbc-url=jdbc:postgresql://db-aules.uji.es:5432/ei102725jhd

# Credenciales
spring.datasource.username=ei102725jhd
spring.datasource.password=aversitrabajamos

# Driver
spring.datasource.driver-class-name=org.postgresql.Driver