spring.application.name=proyectoOvi

spring.datasource.url=jdbc:postgresql://db-aules.uji.es:5432/ei102725jhd
spring.datasource.hikari.jdbc-url=jdbc:postgresql://db-aules.uji.es:5432/ei102725jhd

spring.datasource.username=ei102725jhd
spring.datasource.password=aversitrabajamos

spring.datasource.driver-class-name=org.postgresql.Driver